#!/bin/bash

echo "Enter the path of the directory:"
read directory

declare -a exclude_paths

while true; do
    echo "Enter the path of a file or directory to exclude (or press Enter to finish):"
    read exclude_path
    
    if [[ -z "$exclude_path" ]]; then
        break
    fi
    
    exclude_paths+=("$exclude_path")
done

filename_prefix=$(date "+%Y-%m-%d_%H-%M-%S")

filename="$filename_prefix-service-logs.tar.gz"

tar -czf /backup/"$filename" \
    --exclude="${exclude_paths[@]}" \
    "$directory"

if [[ $? -eq 0 ]]; then
    echo "Backup successfully created as '$filename'"
else
    echo "An error occurred while creating the backup"
fi


Note:- #user to enter the path of the directory (line 3,4)
        #Create an array to store the paths of files or directories to exclude. The variable is an indexed array. 
You cannot unset this attribute. (line 6)
        # Loop to prompt the user to enter additional paths to exclude (line 8-10)
        # Break out of the loop if the user pressed Enter (-z is use for length of string is zero) (line 12-14)
        # Add the excluded path to the array (line 16-17)
        # Set the current timestamp as the filename prefix (line 19)
        # Construct the full filename for the backup archive (line 21)
        # Use tar to create the backup archive, excluding the specified files and directories (line 23-25)
        
